- name: demo on conditions
  hosts: all
  tasks:
    - name: execute this task if distribution is centos
      ansible.builtin.debug:
        msg: welcome to centos
      when: ansible_distribution == "CentOS"

    - name: execute this task if distribution is ubuntu
      ansible.builtin.debug:
        msg: welcome to ubuntu
      when: ansible_distribution == "Ubuntu"  