- name: Playbook to set up the roboshop project
  become: yes
  hosts: local host
  roles:
      - "{{COMPONENT}}"

      #we can localhost whenever infrastructure is dynamic or cant maintain the inventory we will use ansible pull
      
      # ansible pull is going to fetch playbook and will execute locally on top of the server and can do the configuration mgt on top of the 
      #same server and doesnt have to maintain THE SERVER WHICH IS RUNNING ROUND THE CLOCK,ensure ansible server is running round the CLOCK
      
      # no need of ansible controller