- name: demo on vars
  hosts: all
  vars:
    URL: play.google.com
  vars_files: demo-vars.yaml
  vars_prompt: 
  tasks:
    - name: printing the url
      ansible.builtin.debug:
        msg: the value of url is {{URL}}

    - name: printing the task url
      ansible.builtin.debug:
        msg: the value of url is {{URL}}
      vars:
        URL: task.google.com

    - name: printing the url from CLI
      ansible.builtin.debug:
        msg: "{{CMD_URL}}"

    - name: printing the variables from a file
      ansible.builtin.debug:
        msg: "{{GAME_LIVES}}"
